/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Feedback = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'comment' : IDL.Text,
  'timestamp' : IDL.Int,
  'rating' : IDL.Nat,
  'phone' : IDL.Text,
});
export const BusRoute = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Text,
  'duration' : IDL.Text,
  'arrivalTime' : IDL.Text,
  'departureTime' : IDL.Text,
  'fare' : IDL.Float64,
  'from' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllFeedbacks' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAllRoutes' : IDL.Func([], [IDL.Vec(BusRoute)], ['query']),
  'searchRoutes' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(BusRoute)],
      ['query'],
    ),
  'submitFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Feedback = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'comment' : IDL.Text,
    'timestamp' : IDL.Int,
    'rating' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const BusRoute = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Text,
    'duration' : IDL.Text,
    'arrivalTime' : IDL.Text,
    'departureTime' : IDL.Text,
    'fare' : IDL.Float64,
    'from' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllFeedbacks' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAllRoutes' : IDL.Func([], [IDL.Vec(BusRoute)], ['query']),
    'searchRoutes' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(BusRoute)],
        ['query'],
      ),
    'submitFeedback' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };