/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusRoute {
  'id' : bigint,
  'to' : string,
  'duration' : string,
  'arrivalTime' : string,
  'departureTime' : string,
  'fare' : number,
  'from' : string,
}
export interface Feedback {
  'id' : bigint,
  'name' : string,
  'comment' : string,
  'timestamp' : bigint,
  'rating' : bigint,
  'phone' : string,
}
export interface _SERVICE {
  'getAllFeedbacks' : ActorMethod<[], Array<Feedback>>,
  'getAllRoutes' : ActorMethod<[], Array<BusRoute>>,
  'searchRoutes' : ActorMethod<[string, string], Array<BusRoute>>,
  'submitFeedback' : ActorMethod<[string, string, bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];